apiVersion: apps/v1
kind: Deployment
metadata:
  name: script-deployment
  namespace: demo
  labels:
    app: script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: script
  template:
    metadata:
      labels:
        app: script
    spec:
      containers:
      - name: script
        image: linjmeyer/istio-demo-asp # re-using ASP container, but you can use any image with curl installed
        resources:
          limits:
            cpu: 500m
            memory: 200M
        volumeMounts:
          - name: "script-config"
            mountPath: "/demo/"
      restartPolicy: Always
      volumes:
        - name: "script-config"
          configMap:
            name: "script-config"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "script-config"
  namespace: demo
data:
  curl.sh: |
    # Inside cluster curl
    while true; do curl demo/api/demo && echo ""; done

    # Inside cluster curl to canary
    while true; do curl -H "x-demo-environment: canary"  demo/api/demo && echo ""; done

    # Outside cluster curl
    while true; do printf "\n Routing dynamically: \n" && curl demo.lin/api/demo; done

    # Outside cluster curl to canary
    while true; do printf "\n Routing to canary... \n" && curl demo.lin/api/demo -H "x-demo-environment: canary"; done

    # Outside cluster curl to prod
    while true; do printf "\n Routing to prod... \n" && curl demo.lin/api/demo -H "x-demo-environment: prod"; done


